services:

  directors:
    build: .
    container_name: directors
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

networks:
  default:
    name: dockerweb
    external: true
